### ISSUE TITLE
COUNTER

### ISSUE THREAD

**Issue by DenisKantic** [DenisKantic/counterReactJS#1]
To complete this task you need to create the counter using useState hook

- [x] create useState hook 
- [x] make two buttons, one will be "-" ( minus ) and second will be "+" ( plus )
- [x] insert onClick in two buttons so you can call that useState hook

You have video where you can see how it's made but you need to do it with understanding

**Comment by nedimmujcinovic** [comment]
Take a look in my code…

**Comment by DenisKantic** [comment]
Task done, great job !
